version: '3'

services:
  database:
    image: postgres:13.4-alpine
    environment:
      - POSTGRES_USER=hedgedoc
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hedgedoc
    volumes:
      - database:/var/lib/postgresql/data
    restart: always

  identidock:
    build: .
    ports:
      - "5000:5000"
    networks:
      - identinet
    volumes:
      - "./app:/app"
    environment:
      - FLASK_APP=/app/identidock.py
      - FLASK_ENV=development
    command: flask run -h 0.0.0.0

  microblog:
    build: .
    ports:
      - "5001:5000"
    networks:
      - identinet
    volumes:
      - "./app:/app"
    environment:
      - FLASK_APP=/app/identidock.py
      - FLASK_ENV=development
    command: flask run -h 0.0.0.0
    depends_on:
      - database    

  app:
    image: quay.io/hedgedoc/hedgedoc:1.9.9
    environment:
      - CMD_DB_URL=postgres://hedgedoc:password@database:5432/hedgedoc
      - CMD_DOMAIN=localhost
      - CMD_URL_ADDPORT=true
    volumes:
      - uploads:/hedgedoc/public/uploads
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - database

  dnmonster:
    image: amouat/dnmonster:1.0
    networks:
      - identinet

  redis:
    image: redis
    networks:
      - identinet

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    environment:
      - "discovery.seed_hosts=elasticsearch2"
      - "cluster.initial_master_nodes=elasticsearch,elasticsearch2"
    networks:
      - logging-network

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    environment:
      - "discovery.seed_hosts=elasticsearch"
      - "cluster.initial_master_nodes=elasticsearch,elasticsearch2"
    networks:
      - logging-network

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.5.0
    user: root
    depends_on:
      - elasticsearch
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - logging-network
    environment:
      - -strict.perms=false

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.0
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    networks:
      - logging-network
      
volumes:
  database:
  uploads:

networks:
  identinet:
    driver: bridge
  logging-network:
    driver: bridge