version: "3.8"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - logging-network
    ports:
      - 9200:9200
      - 9300:9300

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.13.0
    privileged: true
    user: root
    depends_on:
      - elasticsearch
      - kibana
    volumes:
      - /home/arthur_dev/DEVOPS/TP4-3WACADEMY/elastic-search/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - logging-network
    environment:
      - -strict.perms=false
    command: sh -c './filebeat -e -strict.perms=false modules enable nginx && exec filebeat -e -strict.perms=false'

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.0
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    networks:
      - logging-network

  web:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - logging-network

volumes:
  filebeat-config:

networks:
  logging-network:
    driver: bridge
